//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_2021_g01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prbd_2021_g01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CategoriesView_CancelCategories {
            get {
                return ResourceManager.GetString("CategoriesView_CancelCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CategoriesView_DeleteCategories {
            get {
                return ResourceManager.GetString("CategoriesView_DeleteCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select categories and press the &apos;Del&apos; key to delete.
        /// </summary>
        public static string CategoriesView_DeleteTooltip {
            get {
                return ResourceManager.GetString("CategoriesView_DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CategoriesView_Name {
            get {
                return ResourceManager.GetString("CategoriesView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string CategoriesView_Questions {
            get {
                return ResourceManager.GetString("CategoriesView_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CategoriesView_SaveCategories {
            get {
                return ResourceManager.GetString("CategoriesView_SaveCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist.
        /// </summary>
        public static string Error_DoesNotExist {
            get {
                return ResourceManager.GetString("Error_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already in use.
        /// </summary>
        public static string Error_EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("Error_EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length must be &gt;= 3.
        /// </summary>
        public static string Error_LengthGreaterEqual3 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must match confirm password.
        /// </summary>
        public static string Error_MustMatchConfirmPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must match password.
        /// </summary>
        public static string Error_MustMatchPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        public static string Error_NotAvailable {
            get {
                return ResourceManager.GetString("Error_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong password.
        /// </summary>
        public static string Error_WrongPassword {
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LoginView_Email {
            get {
                return ResourceManager.GetString("LoginView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have a login and a password, click.
        /// </summary>
        public static string LoginView_Message_1 {
            get {
                return ResourceManager.GetString("LoginView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string LoginView_Message_2 {
            get {
                return ResourceManager.GetString("LoginView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to sign-up..
        /// </summary>
        public static string LoginView_Message_3 {
            get {
                return ResourceManager.GetString("LoginView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Languages.
        /// </summary>
        public static string Menu_Languages {
            get {
                return ResourceManager.GetString("Menu_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En_glish.
        /// </summary>
        public static string Menu_Languages_English {
            get {
                return ResourceManager.GetString("Menu_Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _French.
        /// </summary>
        public static string Menu_Languages_French {
            get {
                return ResourceManager.GetString("Menu_Languages_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log_out.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Menu_Profile {
            get {
                return ResourceManager.GetString("Menu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member&apos;s profile.
        /// </summary>
        public static string ProfileView_Title {
            get {
                return ResourceManager.GetString("ProfileView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string QuestionsView_AllCategories {
            get {
                return ResourceManager.GetString("QuestionsView_AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        public static string QuestionsView_Answers {
            get {
                return ResourceManager.GetString("QuestionsView_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available questions :.
        /// </summary>
        public static string QuestionsView_AvailableQuest {
            get {
                return ResourceManager.GetString("QuestionsView_AvailableQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string QuestionsView_Cancel {
            get {
                return ResourceManager.GetString("QuestionsView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories :.
        /// </summary>
        public static string QuestionsView_Categories {
            get {
                return ResourceManager.GetString("QuestionsView_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string QuestionsView_CheckCategories {
            get {
                return ResourceManager.GetString("QuestionsView_CheckCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string QuestionsView_Delete {
            get {
                return ResourceManager.GetString("QuestionsView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected questions :.
        /// </summary>
        public static string QuestionsView_EditSelectedQuestion {
            get {
                return ResourceManager.GetString("QuestionsView_EditSelectedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New question.
        /// </summary>
        public static string QuestionsView_NewQuestion {
            get {
                return ResourceManager.GetString("QuestionsView_NewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string QuestionsView_NoneCategories {
            get {
                return ResourceManager.GetString("QuestionsView_NoneCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string QuestionsView_QuestTitle {
            get {
                return ResourceManager.GetString("QuestionsView_QuestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string QuestionsView_Save {
            get {
                return ResourceManager.GetString("QuestionsView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string QuizDetailView_Cancel {
            get {
                return ResourceManager.GetString("QuizDetailView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string QuizDetailView_Confirm {
            get {
                return ResourceManager.GetString("QuizDetailView_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string QuizDetailView_Delete {
            get {
                return ResourceManager.GetString("QuizDetailView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string QuizDetailView_End {
            get {
                return ResourceManager.GetString("QuizDetailView_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string QuizDetailView_Start {
            get {
                return ResourceManager.GetString("QuizDetailView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string QuizDetailView_Title {
            get {
                return ResourceManager.GetString("QuizDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string QuizDetailView_Weight {
            get {
                return ResourceManager.GetString("QuizDetailView_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string QuizView_Add {
            get {
                return ResourceManager.GetString("QuizView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string QuizView_Cancel {
            get {
                return ResourceManager.GetString("QuizView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string QuizView_Delete {
            get {
                return ResourceManager.GetString("QuizView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select quiz and press the &apos;Del&apos; key to delete.
        /// </summary>
        public static string QuizView_DeleteTooltip {
            get {
                return ResourceManager.GetString("QuizView_DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string QuizView_Edit {
            get {
                return ResourceManager.GetString("QuizView_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string QuizView_End {
            get {
                return ResourceManager.GetString("QuizView_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb of questions.
        /// </summary>
        public static string QuizView_NbQuestions {
            get {
                return ResourceManager.GetString("QuizView_NbQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string QuizView_Start {
            get {
                return ResourceManager.GetString("QuizView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string QuizView_Title {
            get {
                return ResourceManager.GetString("QuizView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SignupView_Cancel {
            get {
                return ResourceManager.GetString("SignupView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SignupView_Email {
            get {
                return ResourceManager.GetString("SignupView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string SignupView_Firstname {
            get {
                return ResourceManager.GetString("SignupView_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string SignupView_Lastname {
            get {
                return ResourceManager.GetString("SignupView_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you already have an account, click.
        /// </summary>
        public static string SignupView_Message_1 {
            get {
                return ResourceManager.GetString("SignupView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string SignupView_Message_2 {
            get {
                return ResourceManager.GetString("SignupView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to sign in..
        /// </summary>
        public static string SignupView_Message_3 {
            get {
                return ResourceManager.GetString("SignupView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignupView_Password {
            get {
                return ResourceManager.GetString("SignupView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordConfirm.
        /// </summary>
        public static string SignupView_PasswordConfirm {
            get {
                return ResourceManager.GetString("SignupView_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignupView_Signup {
            get {
                return ResourceManager.GetString("SignupView_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string SignupView_Title {
            get {
                return ResourceManager.GetString("SignupView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All quizz :.
        /// </summary>
        public static string Student_Courses_AllQuizz {
            get {
                return ResourceManager.GetString("Student_Courses_AllQuizz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses filter :.
        /// </summary>
        public static string Student_Courses_Filter {
            get {
                return ResourceManager.GetString("Student_Courses_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string Student_Courses_QuizEndDate {
            get {
                return ResourceManager.GetString("Student_Courses_QuizEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string Student_Courses_QuizStartDate {
            get {
                return ResourceManager.GetString("Student_Courses_QuizStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Student_Courses_QuizStatus {
            get {
                return ResourceManager.GetString("Student_Courses_QuizStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Student_Courses_QuizTitle {
            get {
                return ResourceManager.GetString("Student_Courses_QuizTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Student_Courses_Teacher {
            get {
                return ResourceManager.GetString("Student_Courses_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Student_Courses_Title {
            get {
                return ResourceManager.GetString("Student_Courses_Title", resourceCulture);
            }
        }
    }
}
