//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_2021_g01.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prbd_2021_g01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à does not exist.
        /// </summary>
<<<<<<< HEAD
        internal static string Error_DoesNotExist {
=======
        public static string Error_DoesNotExist {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("Error_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 3.
        /// </summary>
<<<<<<< HEAD
        internal static string Error_LengthGreaterEqual3 {
=======
        public static string Error_LengthGreaterEqual3 {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match confirm password.
        /// </summary>
<<<<<<< HEAD
        internal static string Error_MustMatchConfirmPassword {
=======
        public static string Error_MustMatchConfirmPassword {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("Error_MustMatchConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match password.
        /// </summary>
<<<<<<< HEAD
        internal static string Error_MustMatchPassword {
=======
        public static string Error_MustMatchPassword {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("Error_MustMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à not available.
        /// </summary>
<<<<<<< HEAD
        internal static string Error_NotAvailable {
=======
        public static string Error_NotAvailable {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("Error_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à required.
        /// </summary>
<<<<<<< HEAD
        internal static string Error_Required {
=======
        public static string Error_Required {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wrong password.
        /// </summary>
<<<<<<< HEAD
        internal static string Error_WrongPassword {
=======
        public static string Error_WrongPassword {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email:.
        /// </summary>
<<<<<<< HEAD
        internal static string LoginView_Email {
=======
        public static string LoginView_Email {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("LoginView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you don&apos;t have a login and a password, click.
        /// </summary>
<<<<<<< HEAD
        internal static string LoginView_Message_1 {
=======
        public static string LoginView_Message_1 {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("LoginView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à here.
        /// </summary>
<<<<<<< HEAD
        internal static string LoginView_Message_2 {
=======
        public static string LoginView_Message_2 {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("LoginView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to sign-up..
        /// </summary>
<<<<<<< HEAD
        internal static string LoginView_Message_3 {
=======
        public static string LoginView_Message_3 {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("LoginView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password:.
        /// </summary>
<<<<<<< HEAD
        internal static string LoginView_Password {
=======
        public static string LoginView_Password {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
<<<<<<< HEAD
        internal static string LoginView_Title {
=======
        public static string LoginView_Title {
>>>>>>> feat_ines
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
    }
}
