//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_2021_g01.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prbd_2021_g01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CategoriesView_CancelCategories {
            get {
                return ResourceManager.GetString("CategoriesView_CancelCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string CategoriesView_DeleteCategories {
            get {
                return ResourceManager.GetString("CategoriesView_DeleteCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select categories and press the &apos;Del&apos; key to delete.
        /// </summary>
        public static string CategoriesView_DeleteTooltip {
            get {
                return ResourceManager.GetString("CategoriesView_DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string CategoriesView_Name {
            get {
                return ResourceManager.GetString("CategoriesView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Questions.
        /// </summary>
        public static string CategoriesView_Questions {
            get {
                return ResourceManager.GetString("CategoriesView_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string CategoriesView_SaveCategories {
            get {
                return ResourceManager.GetString("CategoriesView_SaveCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à does not exist.
        /// </summary>
        public static string Error_DoesNotExist {
            get {
                return ResourceManager.GetString("Error_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email already in use.
        /// </summary>
        public static string Error_EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("Error_EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 3.
        /// </summary>
        public static string Error_LengthGreaterEqual3 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match confirm password.
        /// </summary>
        public static string Error_MustMatchConfirmPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match password.
        /// </summary>
        public static string Error_MustMatchPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à not available.
        /// </summary>
        public static string Error_NotAvailable {
            get {
                return ResourceManager.GetString("Error_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à required.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wrong password.
        /// </summary>
        public static string Error_WrongPassword {
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email:.
        /// </summary>
        public static string LoginView_Email {
            get {
                return ResourceManager.GetString("LoginView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you don&apos;t have a login and a password, click.
        /// </summary>
        public static string LoginView_Message_1 {
            get {
                return ResourceManager.GetString("LoginView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à here.
        /// </summary>
        public static string LoginView_Message_2 {
            get {
                return ResourceManager.GetString("LoginView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to sign-up..
        /// </summary>
        public static string LoginView_Message_3 {
            get {
                return ResourceManager.GetString("LoginView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password:.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Languages.
        /// </summary>
        public static string Menu_Languages {
            get {
                return ResourceManager.GetString("Menu_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En_glish.
        /// </summary>
        public static string Menu_Languages_English {
            get {
                return ResourceManager.GetString("Menu_Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _French.
        /// </summary>
        public static string Menu_Languages_French {
            get {
                return ResourceManager.GetString("Menu_Languages_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log_out.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile.
        /// </summary>
        public static string Menu_Profile {
            get {
                return ResourceManager.GetString("Menu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string ProfileView_Cancel {
            get {
                return ResourceManager.GetString("ProfileView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string ProfileView_Email {
            get {
                return ResourceManager.GetString("ProfileView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Firstname.
        /// </summary>
        public static string ProfileView_Firstname {
            get {
                return ResourceManager.GetString("ProfileView_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lastname.
        /// </summary>
        public static string ProfileView_Lastname {
            get {
                return ResourceManager.GetString("ProfileView_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string ProfileView_Password {
            get {
                return ResourceManager.GetString("ProfileView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PasswordConfirm.
        /// </summary>
        public static string ProfileView_PasswordConfirm {
            get {
                return ResourceManager.GetString("ProfileView_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string ProfileView_Save {
            get {
                return ResourceManager.GetString("ProfileView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Member&apos;s profile.
        /// </summary>
        public static string ProfileView_Title {
            get {
                return ResourceManager.GetString("ProfileView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string SignupView_Cancel {
            get {
                return ResourceManager.GetString("SignupView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string SignupView_Email {
            get {
                return ResourceManager.GetString("SignupView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Firstname.
        /// </summary>
        public static string SignupView_Firstname {
            get {
                return ResourceManager.GetString("SignupView_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lastname.
        /// </summary>
        public static string SignupView_Lastname {
            get {
                return ResourceManager.GetString("SignupView_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you already have an account, click.
        /// </summary>
        public static string SignupView_Message_1 {
            get {
                return ResourceManager.GetString("SignupView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à here.
        /// </summary>
        public static string SignupView_Message_2 {
            get {
                return ResourceManager.GetString("SignupView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to sign in..
        /// </summary>
        public static string SignupView_Message_3 {
            get {
                return ResourceManager.GetString("SignupView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string SignupView_Password {
            get {
                return ResourceManager.GetString("SignupView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PasswordConfirm.
        /// </summary>
        public static string SignupView_PasswordConfirm {
            get {
                return ResourceManager.GetString("SignupView_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign up.
        /// </summary>
        public static string SignupView_Signup {
            get {
                return ResourceManager.GetString("SignupView_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signup.
        /// </summary>
        public static string SignupView_Title {
            get {
                return ResourceManager.GetString("SignupView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All quizz :.
        /// </summary>
        public static string Student_Courses_AllQuizz {
            get {
                return ResourceManager.GetString("Student_Courses_AllQuizz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courses filter :.
        /// </summary>
        public static string Student_Courses_Filter {
            get {
                return ResourceManager.GetString("Student_Courses_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EndDate.
        /// </summary>
        public static string Student_Courses_QuizEndDate {
            get {
                return ResourceManager.GetString("Student_Courses_QuizEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à StartDate.
        /// </summary>
        public static string Student_Courses_QuizStartDate {
            get {
                return ResourceManager.GetString("Student_Courses_QuizStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Student_Courses_QuizStatus {
            get {
                return ResourceManager.GetString("Student_Courses_QuizStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        public static string Student_Courses_QuizTitle {
            get {
                return ResourceManager.GetString("Student_Courses_QuizTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teacher.
        /// </summary>
        public static string Student_Courses_Teacher {
            get {
                return ResourceManager.GetString("Student_Courses_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        public static string Student_Courses_Title {
            get {
                return ResourceManager.GetString("Student_Courses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string StudentCoursesView_Clear {
            get {
                return ResourceManager.GetString("StudentCoursesView_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teacher :.
        /// </summary>
        public static string StudentCoursesView_Teacher {
            get {
                return ResourceManager.GetString("StudentCoursesView_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courses.
        /// </summary>
        public static string StudentMainView_Courses {
            get {
                return ResourceManager.GetString("StudentMainView_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string TeacherCourseDetailView_Cancel {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Categories.
        /// </summary>
        public static string TeacherCourseDetailView_Categories {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string TeacherCourseDetailView_Delete {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string TeacherCourseDetailView_Description {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grades.
        /// </summary>
        public static string TeacherCourseDetailView_Grades {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum capacity.
        /// </summary>
        public static string TeacherCourseDetailView_Maximum_capacity {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Maximum_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Questions.
        /// </summary>
        public static string TeacherCourseDetailView_Questions {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quizzes.
        /// </summary>
        public static string TeacherCourseDetailView_Quizzes {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registrations.
        /// </summary>
        public static string TeacherCourseDetailView_Registrations {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string TeacherCourseDetailView_Save {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teacher.
        /// </summary>
        public static string TeacherCourseDetailView_Teacher {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        public static string TeacherCourseDetailView_Title {
            get {
                return ResourceManager.GetString("TeacherCourseDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate.
        /// </summary>
        public static string TeacherCourseRegistrationsView_Activate {
            get {
                return ResourceManager.GetString("TeacherCourseRegistrationsView_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string TeacherCourseRegistrationsView_Clear {
            get {
                return ResourceManager.GetString("TeacherCourseRegistrationsView_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter :.
        /// </summary>
        public static string TeacherCourseRegistrationsView_Filter {
            get {
                return ResourceManager.GetString("TeacherCourseRegistrationsView_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Firstname.
        /// </summary>
        public static string TeacherCourseRegistrationsView_Firstname {
            get {
                return ResourceManager.GetString("TeacherCourseRegistrationsView_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lastname.
        /// </summary>
        public static string TeacherCourseRegistrationsView_Lastname {
            get {
                return ResourceManager.GetString("TeacherCourseRegistrationsView_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registered students.
        /// </summary>
        public static string TeacherCourseRegistrationsView_Registered_students {
            get {
                return ResourceManager.GetString("TeacherCourseRegistrationsView_Registered_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State.
        /// </summary>
        public static string TeacherCourseRegistrationsView_State {
            get {
                return ResourceManager.GetString("TeacherCourseRegistrationsView_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unregistered students.
        /// </summary>
        public static string TeacherCourseRegistrationsView_Unregistered_students {
            get {
                return ResourceManager.GetString("TeacherCourseRegistrationsView_Unregistered_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string TeacherCoursesView_Clear {
            get {
                return ResourceManager.GetString("TeacherCoursesView_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New course.
        /// </summary>
        public static string TeacherCoursesView_New_course {
            get {
                return ResourceManager.GetString("TeacherCoursesView_New_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Students :.
        /// </summary>
        public static string TeacherCoursesView_Students {
            get {
                return ResourceManager.GetString("TeacherCoursesView_Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teacher :.
        /// </summary>
        public static string TeacherCoursesView_Teacher {
            get {
                return ResourceManager.GetString("TeacherCoursesView_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text filter :.
        /// </summary>
        public static string TeacherCoursesView_Text_filter {
            get {
                return ResourceManager.GetString("TeacherCoursesView_Text_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courses.
        /// </summary>
        public static string TeacherMainView_Courses {
            get {
                return ResourceManager.GetString("TeacherMainView_Courses", resourceCulture);
            }
        }
    }
}
